gallery/urls.py
from django.conf.urls import url
from . import views

app_name = 'gallery'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

main_menu/urls.py
from django.conf.urls import url
from . import views

app_name = 'main_menu'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^practicals/', include('practicals.urls')),
    url(r'^gallery/', include('gallery.urls')),
    url(r'^', include('main_menu.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

practicals/urls.py
from django.conf.urls import url
from . import views

app_name = 'practicals'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<practical_id>[0-9]+)/$', views.detail, name='detail'),
]

gallery/models.py
from django.db import models

# Create your models here.

main_menu/models.py
from django.db import models

# Create your models here.

practicals/models.py
from django.db import models

class Subject(models.Model):
    subName = models.CharField(max_length=100)

    def __str__(self):
        return self.subName

class Practical(models.Model):
    title = models.CharField(max_length=500)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Photo(models.Model):
    practical = models.ForeignKey(Practical, blank=False, on_delete=models.CASCADE)
    index = models.IntegerField()
    image = models.ImageField()

    def __str__(self):
        return self.practical.title + ' - ' + str(self.index)

gallery/views.py
from django.shortcuts import render, get_object_or_404

def index(request):
    return render(request, 'gallery/index.html')

main_menu/views.py
from django.shortcuts import render, get_object_or_404

def index(request):
    return render(request, 'main_menu/index.html')

practicals/views.py
from django.shortcuts import render, get_object_or_404
from .models import Subject,Practical,Photo
from django.db.models import Q
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage

def index(request):
    practicals = Practical.objects.all()
    subjects = Subject.objects.all()
    query = request.GET.get("q")
    if query:
        practicals = practicals.filter(
            Q(title__icontains=query)
        ).distinct()
        subjects = Subject.objects.filter(practical=practicals)
        return render(request, 'practicals/index.html',{'practicals': practicals, 'subjects': subjects})
    else:
        return render(request, 'practicals/index.html',{'practicals': practicals, 'subjects': subjects})

def detail(request, practical_id):
    photo = Photo.objects.filter(practical=practical_id)
    practical = get_object_or_404(Practical, pk=practical_id)
    paginator= Paginator(photo,1)

    page = request.GET.get('page')
    try:
       photo = paginator.page(page)
    except PageNotAnInteger:
       photo = paginator.page(1)
    except EmptyPage:
       photo = paginator.page(paginator.num_pages)

    return render(request, 'practicals/detail.html',{'photo':photo, 'practical':practical})

gallery/templates/gallery/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Gallery</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'practicals/css/bootstrap.css'%} "/>
</head>
<body>
<div class="container">
    <div class="jumbotron">
    <h1>Welcome to Gallery</h1>
    </div>
</div>

</body>
</html>

main_menu/templates/main_menu/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>HomePage</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'main_menu/css/bootstrap.css'%} "/>
    <link rel="stylesheet" type="text/css" href="{% static 'main_menu/css/bootstrap-glyphicons.css'%} "/>
    <link rel="stylesheet" type="text/css" href="{% static 'main_menu/css/style.css' %}"/>
  </head>
  <body>
      <div class="row" id="features">
      <a href="{% url 'practicals:index' %}">
        <div class="col-sm-6 feature1" > Lab Reports</div></a>

        <a href="#">
        <div class="col-sm-6 feature2" >Travel Guide</div></a>
       </div>

       <div class="row" id="features">
        <a href="#"><div class="col-sm-6 feature3" >
          Articles</div></a>

        <a href="{% url 'gallery:index' %}">
        <div class="col-sm-6 feature4" >
          Gallery</div></a>
      </div>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

practicals/templates/practicals/base.html
<!DOCTYPE html>
<html lang="en" ng-app>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Lab reports{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'practicals/css/bootstrap.css'%} "/>
    <link rel="stylesheet" type="text/css" href="{% static 'practicals/css/style.css'%} "/>
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
</head>

<body>
<div class="container">
    <div class="jumbotron head">
        {% block body %}
        {% endblock %}
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="{% static 'practicals/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.9/angular.min.js"></script>
</body>
</html>

practicals/templates/practicals/detail.html
{% extends 'practicals/base.html' %}
    {% block title %}{{ practical }}{% endblock %}

{% block body %}
    <div class="row">


    <div class="back-btn">
        <a href="{% url 'practicals:index' %}">
            <button type="button" class="btn btn-success btn-sm">
                <span class="glyphicon glyphicon-backward"> Back</span>
            </button>
        </a>
    </div>
    <div class="home-btn">
        <a href="{% url 'main_menu:index' %}">
        <button type="button" class="btn btn-success btn-sm">
            <span class="glyphicon glyphicon-home"> Home</span>
        </button>
        </a>
    </div>
    <br><br>

{% for phot in photo %}
    <div class="heading">{{ practical }}</div>
        <div class="col-md-offset-1 col-md-10">
            {% if phot.image %}
                 <img src="{{ phot.image.url }}" class="img-responsive">
             {% else %}
                 <h3>No image to display</h3>
            {% endif %}
            <br>

            <a target="_blank" href="{{ phot.image.url }}">
                <button type="button" class="btn btn-success btn-sm">
                    <span class="glyphicon glyphicon-eye-open"></span>&nbsp;View full screen
                </button>
            </a>
        </div>
    </div>
    `{% endfor %}

    <nav>
    <div class="text-center">
    <ul class="pagination pagination-centered">
        {% if photo.has_previous %}
                <li><a href="?page={{ photo.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="disabled"><span>&laquo;</span></li>
            {% endif %}

        {% for i in photo.paginator.page_range %}
         {% if photo.number == i %}
            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
         {% else %}
             <li><a href="?page={{ i }}">{{ i }}</a></li>
         {% endif %}
        {% endfor %}

        {% if photo.has_next %}
                <li><a href="?page={{ photo.next_page_number }}">&raquo</a></li>
            {% else %}
                <li class="disabled"><span>&raquo;</span></li>
            {% endif %}

    </ul>
    </div>
    </nav>
{% endblock %}

practicals/templates/practicals/index.html
{% extends 'practicals/base.html' %}

{% block body %}
    <div id="websiteLogo"><a href="{% url 'main_menu:index' %}"><img src="..\..\static\practicals\images\logo.png"></a></div>
        <div id="websiteTitle">Lab reports</div>
    </div>
    </div>
    <div class="container">
    <div class="jumbotron">
        <div class="row">
          <div class="col-md-offset-2 col-md-8">
            <form role="search" method="get" action="{% url 'practicals:index' %}">
            <div class="input-group input-group-lg">
                <input type="text" class="form-control" placeholder="search by title" name="q" value="{{ request.GET.q }}">
                <span class="input-group-btn">
                  <button type="submit" class="btn btn-default">Search</button>
                 </span>
             </div>
            </form>
          </div>
        </div>

        <BR><BR>

        <div class="row">
            <div class="col-md-offset-1 col-md-10">
                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                <div class="panel panel-default">
                  {% for subject in subjects %}
                     <div class="panel-heading" role="tab">
                     <h4 class="panel-title">
                      <a role="button" data-toggle="collapse" data-parent="#accordion" href="#{{ subject.id }}"
                         aria-expanded="true"> {{ subject }}</a></h4>
                     </div>

                  <div id="{{ subject.id }}">
                  {% for practical in practicals %}
                    {% if practical.subject == subject %}
                    <div  class="panel-collapse collapse in" role="tabpanel">
                      <div class="panel-body">
                        <a href="{% url 'practicals:detail' practical.id %}">{{ practical }}</a>
                      </div>
                    </div>
                     {% endif %}
                  {% endfor %}
                  </div>
                {% endfor %}
              </div>
              </div>
            </div>
        </div>

{% endblock %}

practicals/templates/practicals/index1.html
{% extends 'practicals/base.html' %}

{% block body %}
    <a href="{% url 'main_menu:index' %}"><img src="../../../media/logo.png" id="websiteLogo"></a>
        <span id="websiteTitle">New think tank</span>
    </div>
    </div>
    <div class="container">
    <div class="jumbotron">
        <div class="row">
          <div class="col-md-offset-2 col-md-8">
            <form role="search" method="get" action="{% url 'practicals:index' %}">
            <div class="input-group input-group-lg">
                <input type="text" class="form-control" placeholder="search by title" name="q" value="{{ request.GET.q }}">
                <span class="input-group-btn">
                  <button type="submit" class="btn btn-default">Search</button>
                 </span>
             </div>
            </form>
          </div>
        </div>

        <BR><BR>

        <div class="row">
            <div class="col-md-offset-1 col-md-10">

<div class="panel-group" id="accordion">
    {% for subject in subjects  %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse{{ forloop.counter }}">
                    {{ subject }}
                </a>
            </h4>
        </div>
    {% for practical in practicals %}
        {% if practical.subject == subject %}
        <div id="collapse{{ forloop.counter }}" class="panel-collapse collapse">
            <div class="panel-body">
                <a href="{% url 'practicals:detail' practical.id %}">{{ practical }}</a>
            </div>
        </div>
    </div>{% endif %}
                  {% endfor %}
    {% endfor %}
</div>

{% endblock %}